// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using miniproject.Model;
//
//    var courses = Courses.FromJson(jsonString);

namespace miniproject.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Courses
    {
        [JsonProperty("course_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CourseId { get; set; }

        [JsonProperty("course_name")]
        public string CourseName { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("term")]
        public long Term { get; set; }

        [JsonProperty("credits")]
        public long Credits { get; set; }

        [JsonProperty("prerequisites")]
        public List<object> Prerequisites { get; set; }

        [JsonProperty("instructor")]
        public string Instructor { get; set; }
    }

    public partial class Courses
    {
        public static List<Courses> FromJson(string json) => JsonConvert.DeserializeObject<List<Courses>>(json, miniproject.Model.Converter.Settings);
    }

    public static class CoursesSerialize
    {
        public static string ToJson(this List<Courses> self) => JsonConvert.SerializeObject(self, miniproject.Model.Converter.Settings);
    }

    internal static class CoursesConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
